-   name: run_failure_script_1
    triggers:
        -   python.script.fail.1
    command: "$HOME/workspace/angora/test/fail_test_1.py"
    log: "$HOME/workspace/angora/logs/"

-   name: run_arg_test_script
    triggers:
        -   python.script.argtest
    command: "$HOME/workspace/angora/test/arg_test.py"
    log: "$HOME/workspace/angora/logs/"