-   name: print_environment_variables
    triggers:
        -   shell.print.env
    command: "env"
    log: "$HOME/workspace/angora/logs/"
    messages:
        -   shell.print.message.test

-   name: print_test_message
    triggers:
        -   shell.print.message.test
    command: "echo 'THIS IS A TEST'"
    log: "$HOME/workspace/angora/logs/"

-   name: test_date
    triggers: shell.print.date
    command: "date"
    log: "$HOME/workspace/angora/logs/"

-   name: test_date_2
    triggers: shell.print.date.2
    command: "echo $(date '+%Y%m%d')"
    log: "$HOME/workspace/angora/logs/"
